#!/bin/bash

cd $OPENSHIFT_REPO_DIR
nohup java -jar target/scala-openshift-0.0.1-SNAPSHOT-jar-with-dependencies.jar -com.twitter.finatra.config.port="$OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT" -com.twitter.finatra.config.adminPort='' > ${OPENSHIFT_DIY_LOG_DIR}/application.log 2>&1 &